<a href="https://colab.research.google.com/github/xavierbarriga/diplomadoML/blob/main/XBS_Practica2_opcion1_prediccion_precios_movil.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Xavier Eduardo Barriga Sinisterra**

# Practica 2. Opcion 1 (Prediccion Precio de un Móvil)

<img src="https://www.neuraldojo.org/media/bg_mobile.jpeg"
     alt="Markdown Monster icon"
     style="float: left; margin-right: 10px;" width="100%"/>

### **Nombre Alumno:**
**Contexto**

Bob ha comenzado su propia empresa de telefonía móvil. Quiere dar una pelea dura a las grandes empresas como Apple, Samsung, etc.

No sabe cómo estimar el precio de los móviles que fabrica su empresa. En este competitivo mercado de telefonía móvil no se puede simplemente asumir cosas. Para resolver este problema, recopila datos de ventas de teléfonos móviles de varias empresas.

Bob quiere averiguar alguna relación entre las funciones de un teléfono móvil (p. ej., RAM, memoria interna, etc.) y su precio de venta. Pero no es tan bueno en Machine Learning. Así que necesita tu ayuda para resolver este problema.

En este problema, no tiene que predecir el precio real, sino un rango de precios que indica qué tan alto es el precio

##Objetivo de la practica

- Parte 1. En un Notebook construya un modelo para predecir el rango de precio de un móvil.
- Parte 2. Publique y comparta su Notebook en [Github.com](https://www.github.com)
- Parte 3. En base al trabajo desarrollado y los hallazasgos redacte, publique y comparta un articulo en [medium.com](https://www.medium.com)

##Criterios de Evaluación

Parte 1.

- Seguir todos los pasos de un proceso ML:
    - Identificación del Problema
    - Importación de datos
    - EDA
    - Modelado (probar al menos tres algoritmos)
    - Evaluación (al menos dos métricas)
    - Hypertunning con Gridsearch
    - Selección del Modelo
    - Resultados y Conclusiones

- Todo el código del proyecto esté contenido en un cuaderno o script de Jupyter o Google Colab. 
- Demuestre una ejecución y salida exitosas del código, sin errores.
- Escriba código que esté bien documentado y use funciones y clases según sea necesario.

Parte 2.

El repositorio en Github debe conteener:
- El cuaderno *.ipynb
- README.md, que explique el problema, una descripcion del dataset, requerimientos y librerias para la correcta ejecución del codigo, Resultados y conclusiones
- Licencia del codigo

Parte 3.

El articulo en medium debera contener las siguientes secciones:

- Introduccion
- Problema
- Analisis Exploratorio explicando aspectos relevantes de lo encontrado
- Modelado ML
- Evaluación y Hipertunning
- Resultados y Conclusiones
- Incluir referencia on enlace al codigo disponible en su cuenta github.

##Dataset

Puede descargar el dataset aqui: https://neuraldojo.org/media/mobile/archive.zip

##Método de Entrega del trabajo:

Enviar e mi correo: necrus.aikon@gmail.com, Asunto: Practica 2 (Stroke) lo siguiente:
- Enlace o archivo adjunto del codigo en colab
- Enlace github
- Enlace medium

In [1]:
#importamos las librerias
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
#Importamos el Dataset
!wget https://neuraldojo.org/media/mobile/archive.zip
!unzip archive.zip

--2022-04-11 03:51:59--  https://neuraldojo.org/media/mobile/archive.zip
Resolving neuraldojo.org (neuraldojo.org)... 143.95.32.198
Connecting to neuraldojo.org (neuraldojo.org)|143.95.32.198|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72340 (71K) [application/zip]
Saving to: ‘archive.zip.1’

archive.zip.1       100%[===================>]  70.64K  --.-KB/s    in 0.1s

2022-04-11 03:51:59 (727 KB/s) - ‘archive.zip.1’ saved [72340/72340]

Archive:  archive.zip
  inflating: test.csv
  inflating: train.csv

In [4]:
df_movil = pd.read_csv('test.csv')

In [7]:
df_movil.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1

In [9]:
df_movil.shape

(1000, 21)

In [10]:
df_movil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB